Schedule 관련 API 구현
Likelion-YeungNam-Univ/12th-holing-was pull request #14
Opened 2024-07-17 10:45 UTC by Jsplix

## 🚀 작업 내용 및 이슈
- 부부 캘린더 메뉴의 기능 (일정 관련 CRUD) API 구현

## ✅ 기능 테스트
- ### 일정 등록 api ( [POST] /calendar/create )
![일정 등록](https://github.com/user-attachments/assets/785119fa-b20b-4cbb-9224-bc13d40a5e6c)

- ### 일정 조회 api ( [GET] /calendar?user={userId}&date={YYYY-MM-DD} )
![일정 조회](https://github.com/user-attachments/assets/a1033940-5a18-4a4e-9b29-896b12245c7f)

- ### 일정 수정 api ( [PUT] /calendar/{scheduleId} )
![일정 수정](https://github.com/user-attachments/assets/aa98a0e2-01e9-4b41-bf7f-ee670f12fa08)

- ### 일정 삭제 api ( [DELETE /calendar/{scheduleId} )
![일정 삭제](https://github.com/user-attachments/assets/359faac3-c07a-48a7-b6ac-b5527b0ed16e)

## 📌 참고사항
- 예외 처리가 생각보다 헷갈리는게 좀 있었는데 한번 검토 부탁드립니다!
  - ex) 사용자가 특정 날짜를 클릭하고 일정을 수정할텐데 삭제 된 일정에 대한 경우를 굳이 예외 처리 할 필요가 있는가?
- 기능 명세를 보고 API를 구현하였는데 추가적으로 필요한 기능이 있는지도 검토 부탁드립니다 😅 
- 컨벤션의 경우도 조금 고민을 했습니다!
  - ex) calendar인데 메소드명은 schedule로 하는게 괜찮은가..? 이외에도 controller나 service 함수 네이밍이 적절한지..
- 더 좋은 방법이나 제가 잘못 작성한 부분이 있다면 말씀 부탁드립니다 :)
- Issue는 이미 closed가 되어있어서 따로 추가하진 않겠습니다

2024-07-17 12:08 UTC, jinlee1703 reviewed
코멘트 남기고 갑니다 ㅎㅎ

2024-07-17 12:08 UTC, jinlee1703 commented on src/main/java/com/example/atm/bounded_context/schedule/controller/ScheduleController.java
> +    @PostMapping("/create")
어떻게하면 좀 더 RESTful하게 API를 구현할 수 있을 지 고민해보면 좋겠네요 ㅎㅎ

2024-07-17 12:08 UTC, jinlee1703 commented on src/main/java/com/example/atm/bounded_context/schedule/service/ScheduleService.java
> +    private UserRepository userRepository;
현재는 필드 주입을 통해 의존성 주입을 하고 있는데, 다른 방법은 없을까요?

2024-07-17 13:22 UTC, iampingu99 commented on src/main/java/com/example/atm/bounded_context/schedule/controller/ScheduleController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
나중에 예외처리에 대해서 한번 의논해봐야겠어요~

2024-07-17 13:22 UTC, iampingu99 commented on src/main/java/com/example/atm/bounded_context/schedule/controller/ScheduleController.java
> +    @PostMapping("/create")
동의합니다~

2024-07-17 13:26 UTC, iampingu99 commented on src/main/java/com/example/atm/bounded_context/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByUserIdAndStartAtBetweenOrderByStartAtAsc(Long userId, LocalDateTime startAt, LocalDateTime finishAt);
JPA의 네이밍 규칙으로 메서드 이름이 너무 길어진다면 JPQL이나 native SQL을 사용하여 새로 쿼리를 생성하는 방식도 좋을 것 같다는 생각이듭니다!

2024-07-17 14:23 UTC, iampingu99 requested changes
> 예외 처리가 생각보다 헷갈리는게 좀 있었는데 한번 검토 부탁드립니다!
ex) 사용자가 특정 날짜를 클릭하고 일정을 수정할텐데 삭제 된 일정에 대한 경우를 굳이 예외 처리 할 필요가 있는가?

저는 애플리케이션의 사용자 경험을 향상시켜주기 위해 예외처리가 구체적이어야 한다고 생각합니다. 예를 들어서 비밀번호를 입력했을 때 특수문자가 꼭 포함되어야 한다던지, 몇 자 이상이어야 한다던지 사용자의 입력에 따라 다른 메세지를 보여주면 좋겠죠.
하지만 서버단에서 예외는 코드 유지보수가 가능할 정도라면 어느정도 포괄적으로 작성해도 된다고 생각합니다. delete 또는 update 에서 userRepository 의 findById 메서드를 사용할 때 "삭제할 객체가 없다" 또는 "업데이트할 객체가 없다" 의 차이가 사용자보다는 개발자에게 코드 유지보수에 도움을 주므로 개개인에 따라 설정할 수 있을 것 같다는 생각이 듭니다.

> 기능 명세를 보고 API를 구현하였는데 추가적으로 필요한 기능이 있는지도 검토 부탁드립니다 😅

프론트에서 화면을 구성하기 위해서 어떤 반환값이 필요한 지 고민해보시면 좋을 것 같습니다. 현재 일정 관련 CRUD는 잘 작성해주신 것 같습니다. 

> 컨벤션의 경우도 조금 고민을 했습니다!
ex) calendar인데 메소드명은 schedule로 하는게 괜찮은가..? 이외에도 controller나 service 함수 네이밍이 적절한지..

일정에 관해 CRUD를 진행하므로 prefix calendar 보다는 schedule 이 더 명확해 보입니다. 

리뷰 확인해보시고 해결되면 approve 하겠습니다~

추가로 이전에 JwtProvider 를 작성해서 서비스에서 JWT 를 인증수단으로 사용하려 했습니다. 이렇게 되면 파싱을 통해 payload 의 userId를 가져올 수 있습니다. 이에 대한 설명이 부족했네요 더 이야기 나눠봅시다!

2024-07-17 14:23 UTC, iampingu99 commented on src/main/java/com/example/atm/bounded_context/schedule/service/ScheduleService.java
> +        scheduleRepository.save(schedule);
기존의 스케줄을 삭제하고 추가하는 이유는 무엇인가요?

2024-07-17 14:23 UTC, iampingu99 commented on src/main/java/com/example/atm/bounded_context/schedule/service/ScheduleService.java
> +        return ScheduleResponseDto.fromEntity(schedule);
영속성 컨텍스트를 잘 활용하면 save 를 하지 않아도 될 것 같은데 어떻게 생각하시나요?

2024-07-17 17:07 UTC, iampingu99 approved these changes
확인했습니다 👍

2024-07-17 17:07 UTC, merged

2024-07-18 02:12 UTC, Jsplix commented on src/main/java/com/example/atm/bounded_context/schedule/service/ScheduleService.java
> +    private UserRepository userRepository;
DI에 대해서 좀 더 공부하고 다음 API 구현 때 적용해보도록 하겠습니다! 😃

2024-07-18 02:12 UTC, Jsplix commented on src/main/java/com/example/atm/bounded_context/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByUserIdAndStartAtBetweenOrderByStartAtAsc(Long userId, LocalDateTime startAt, LocalDateTime finishAt);
추후에 공부해보도록 하겠습니다!