로그인 및 회원가입 API 수정, Auth 명세서 작성
Likelion-YeungNam-Univ/12th-holing-was pull request #31
Opened 2024-07-20 13:21 UTC by iampingu99

### 🔥 작업 동기 및 이슈

- close: #

### 🛠️ 변경 사항

- 로그인 및 회원가입 API 수정
    - 최초가입자는 가입 이전에 테스트를 진행하게 되므로 요청 시 엑세스 토큰 뿐만 아니라 테스트에서 얻는 메타정보 성별, 월경유무를 포함하도록 합니다. 성별이 여자인 경우에만 월경 유무에 값이 적용됩니다.
    - 기존가입자는 엑세스 토큰만을 가지고 소셜 인증 서버에서 얻을 수 있는 정보만을 업데이트 하도록 합니다.
    - 비밀번호와 짝꿍 속성을 제외한 나머지 속성을 not null 로 수정하였습니다.
- auth API 명세서 작성  
- jwt 관련 예외 코드 및 핸들러 추가

### ☑️ 테스트 결과

- {{iip}}/auth/signIn FEMALE + false -> FEMALE + false
    <img width="1013" alt="h1" src="https://github.com/user-attachments/assets/251ac0de-e34a-4100-b1cd-ad5e4f41019b">

- {{iip}}/auth/signIn FEMALE + true -> FEMALE + true
    <img width="1008" alt="image" src="https://github.com/user-attachments/assets/e77e9330-6d3e-4a38-8a04-d3816a0bb4c0">

- {{ip}}/auth/signIn MATE + true -> MALE -> false
    <img width="1011" alt="12" src="https://github.com/user-attachments/assets/1802c9e9-f73e-4920-bcfd-11c2c3e07160">

### 🌟 참고사항

- 지난 코드에서 작성된 user api 명세서를 swagger 에서 확인해보시면 좋을 것 같습니다.

2024-07-20 17:28 UTC, Jsplix requested changes
에러 코드 부분 다른게 있어서 고것만 확인해보시면 될 것 같습니다!
항상 보고 많이 배우네여 👍 
수고하셨습니다 🙇‍♂️ !!

2024-07-20 17:28 UTC, Jsplix commented on src/main/java/com/example/holing/bounded_context/user/entity/User.java
>      private Integer point;
저는 Mission Entity의 reward를 int형으로 선언해놓았는데, 혹시 Integer를 사용하신 이유가 있으신지 궁금합니다..!
뭔가 자료형을 통일하면 좋을 것 같다는 생각이 드네용!

2024-07-20 17:28 UTC, Jsplix commented on src/main/java/com/example/holing/bounded_context/auth/api/AuthApi.java
> +                                                                                    "cause": "401 Unauthorized: \\"{\\"msg\\":\\"this access token does not exist\\",\\"code\\":-401}\\""
responseCode와 밑의 cause에 적힌 에러 코드가 다른 것 같습니다!

2024-07-20 17:28 UTC, Jsplix commented on src/main/java/com/example/holing/bounded_context/auth/api/AuthApi.java
> +    })
여기도 에러코드만 수정하시면 될 것 같습니당 :)

2024-07-20 21:43 UTC, iampingu99 commented on src/main/java/com/example/holing/bounded_context/user/entity/User.java
>      private Integer point;
null 값이 들어갈 수 있는 래퍼 클래스를 사용하면 원시 클래스를 사용했을 때 null 에러가 발생하지 않도록 하기 위해서 였는데, nullable 하지 않다면 원시 타입을 사용하면 될 것 같네요 수정하겠습니다!

2024-07-20 21:45 UTC, iampingu99 commented on src/main/java/com/example/holing/bounded_context/auth/api/AuthApi.java
> +                                                                                    "cause": "401 Unauthorized: \\"{\\"msg\\":\\"this access token does not exist\\",\\"code\\":-401}\\""
다른 API 를 사용하면서 받아낸 message 값이라 어떤 값이 올지 모릅니다. 대부분 401 관련 메세지가 올 것으로 예상되지만 저희 가 400으로 반환해주면 처리가 쉬워질 것으로 생각됩니다!

2024-07-20 21:47 UTC, iampingu99 commented on src/main/java/com/example/holing/bounded_context/auth/api/AuthApi.java
> +    })
swagger-ui 로 볼 때 편하지만 애노테이션과 텍스트로 꽉꽉 들어찬 코드를 리뷰하시기 힘들었을 것 같은데, 꼼꼼하게 봐주셔서 감사합니다!!!1

2024-07-21 02:06 UTC, Jsplix approved these changes
늦은 시간까지 고생하셨습니다 !
저도 최대한 빠르게 완성해서 PR 올릴게요 😄

2024-07-21 02:06 UTC, Jsplix commented on src/main/java/com/example/holing/bounded_context/auth/api/AuthApi.java
> +                                                                                    "cause": "401 Unauthorized: \\"{\\"msg\\":\\"this access token does not exist\\",\\"code\\":-401}\\""
앗 그런 의도가 있었군여! 잘 몰랐네요 ㅎㅎ;;

2024-07-21 09:01 UTC, merged